env:
  global:
    - CC_TEST_REPORTER_ID=a191fa9b274de51ffdac1924012aa63e6fd86fc0fea1a70606f058dd9421128e
language: node_js
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test-ci
after_script:
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
node_js:
  - 10
  - 8